name: test

on:
 push:
   branches:
     - master

# on:
#   pull_request:
#     types: [closed]
#     branches:
#       - master
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

    # 서버에 접속하여 배포 실행          
    - name: SSH into server and deploy
      working-directory: for-kimchi-client
      run: |   
        ssh -vvv -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no  ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'

        echo '== build end =   =='
